### ISSUE TITLE
Syntax error CLOUDALM template

### ISSUE THREAD

**Issue by litlepoop** [LMS235/SAP-Table-EXP-IMP-for-SystemCopy#1]
When executing R3trans with  the CLOUDALM.tpl it will result in a syntax error:

4 ETW000 R3trans was called as follows: R3trans -w /home/se1adm/SAP-Table-EXP-IMP-for-SystemCopy-1.5/expimp/CLOUDALM.exp.log /home/se1adm/SAP-Table-EXP-IMP-for-SystemCopy-1.5/expimp/CLOUDALM.tpl
2EETW000 error when reading the R3trans controlfile
2EETW000 syntax error at line 4, symbol "/".
2EETW000 error when reading the R3trans controlfile
2EETW000 syntax error at line 4, symbol "/".
2EETW000 error when reading the R3trans controlfile
2EETW000 unknown option SELECT = yes at line 5, symbol "select".
[...]

Full Log:
[CLOUDALM.exp.log](https://github.com/LMS235/SAP-Table-EXP-IMP-for-SystemCopy/files/14374357/CLOUDALM.exp.log)

**Comment by litlepoop** [comment]
The exact same error seems to occur when executing the GTSSL template.
The common denominator seems to be that both templates contains tables with leading namespace.
They probably need to be put in quotation marks, or the slash needs to be escaped.

**Comment by LMS235** [comment]
fixed in https://github.com/LMS235/SAP-Table-EXP-IMP-for-SystemCopy/commit/7a88f2cd51e06bf3946e8f3edf3a4ca35ec19eef

new Release https://github.com/LMS235/SAP-Table-EXP-IMP-for-SystemCopy/releases/tag/1.6
